version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:51"
      timezone: "Europe/Stockholm"
    vendor: true
    # Disable version updates for now
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        dependency-type: "all"

