name: apt

on:
  push:
    paths:
    - '.github/workflows/apt.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - run: cat /etc/apt/apt.conf.d/80-retries
    #   if: always()

    - run: whoami
      if: always()

    - run: sudo whoami
      if: always()

    - run: ls -ahl /etc/apt/
      if: always()

    # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message
    - run: echo "::warning file=app.js,line=1,col=5::Missing semicolon"

    - run: ls -ahl /etc/apt/apt.conf.d/
      if: always()

    # - run: echo "APT::Acquire::Retries \"3\";" | sudo tee /etc/apt/apt.conf.d/80-retries
    #   if: always()

    # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
    - run: echo "::error file=app.js,line=10,col=15::Something went wrong"

    - run: sudo apt-get --option="APT::Acquire::Retries=3" update
      if: always()
