name: github context

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Ruby]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - id: info
        run: echo "::set-output name=version::$(git describe --abbrev=0)"
      - run: echo "Latest version is ${{ steps.info.outputs.version }}"

      - run: echo "$GITHUB_JOB"
      - run: echo "$GITHUB_ACTION"
      - run: echo "$GITHUB_RUN_ID"
      - run: echo "$GITHUB_REF"
      - run: echo "$GITHUB_REPOSITORY"
      - run: echo "$GITHUB_SHA"
      - run: echo "$GITHUB_HEAD_REF"
      - run: echo "$USER"
      - run: echo "$HOME"
      - run: echo "$(id)"
      - run: echo "${USER}"
      - name: USER test2
        run: |
          echo tut1
          echo ${USER}
          echo tut2

      - run: cat $GITHUB_EVENT_PATH

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
