name: Memcached

on:
  push:
    paths:
    - '.github/workflows/memcached.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo MEMCACHIER_SERVERS
        run: echo "$MEMCACHIER_SERVERS"
        env:
          # get randomly assigned published ports
          MEMCACHIER_SERVERS: "localhost:${{ job.services.memcached.ports[11211] }}"
    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211/udp
        # needed because the memcached container does not provide a healthcheck
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
