name: CI

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      CI: external
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [3.1]
    steps:
      - run: ssh -V
      - run: ssh -v localhost
      #- uses: actions/checkout@v4
      #- uses: ruby/setup-ruby@v1
      #  with:
      #    ruby-version: '${{ matrix.ruby }}'
      #- run: ruby ci.rb
