name: Ruby

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/ruby.yml'
    - '.ruby-version'
    - 'bin/test'
    - 'Gemfile'
    - 'Gemfile.lock'

jobs:
  windows:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [head]
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby -v
      - run: ruby -e 'p RUBY_ENGINE'
      - run: ruby -e 'p RUBY_PLATFORM'
      - run: ruby -e 'p RUBY_DESCRIPTION'
      - run: bundle -v
      - run: umask
      - run: umask 0002
      - run: umask
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: |
        echo "::echo::on"
        FOO="foo bar baz"
        echo "$FOO"
        touch "$FOO.txt"
        ls -ahl
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler: "Gemfile.lock"
        bundler-cache: true
    - run:  ruby -v
    - run:  bundle -v
    - run:  gem -v
    - run:  bin/test
    - run:  bundle install
    - run:  ruby tut.rb
    - name: ruby tut.rb with ENV
      run:  ruby tut.rb
      env:
        AMQP_PORT: 1337
