name: Testing workflow_dispatch

on:
  repository_dispatch:
    types: [foobar]
  workflow_dispatch:
    inputs:
      foo:
        description: 'Foo'
        required: true
        type: string 
      bar:
        description: 'Bar'
        required: true
        type: string

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if test -n "${{ inputs.foo }}"
          then
            matrix="{\"foo\":[\"${{ inputs.foo }}\"], \"bar\":[\"${{ inputs.bar }}\"]}"
          else
            matrix="{\"foo\":[\"${{ github.event.client_payload.foos }}\"], \"bar\":[\"${{ github.event.client_payload.bars }}\"]}"
          fi
          echo ::set-output name=matrix::{\"include\":$(echo $matrix)}
  build:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    timeout-minutes: 3
    steps:
      - name: Echo matrix values
        run: |
          echo foo=${{ matrix.foo }}
          echo bar=${{ matrix.bar }}
