name: workflow_dispatch to repo dispatch

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Foo'
        required: true
        type: string 
      bar:
        description: 'Bar'
        required: true
        type: string

jobs:
  build:
    name: inputs foo=${{ inputs.foo }} bar=${{ inputs.bar }}
    runs-on: ubuntu-latest
    steps:
      - name: input values foo=${{ inputs.foo }} bar=${{ inputs.bar }}
        run: |
          echo foo=${{ inputs.foo }}
          echo bar=${{ inputs.bar }}
      - name: dispatch
        run: |
          curl \
            --silent \
            --verbose \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            --data '{"event_type":"repo-dispatch","client_payload":{"foos":["${{ inputs.foo }}"],"bars":["${{ inputs.bar }}"]}}'
